-- =====================================================================
-- Flyway Migration V132: Seed AIPrep Question Bank
-- Target Table: ai_prep_question_bank
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. GENERAL INTRO (Exactly 1 Question)
-- ---------------------------------------------------------------------
INSERT INTO `ai_prep_question_bank` 
  (`category`, `sub_category`, `difficulty_level`, `question_text`, `ideal_answer_rubric`, `relevant_skills_json`, `is_active`)
VALUES 
(
  'GENERAL', 
  'background_summary', 
  'EASY', 
  'Hello, please introduce yourself and your background?', 
  'Look for a concise 2-3 minute background summary highlighting relevant software/AI engineering experience, key impact metrics, and alignment with target role goals.', 
  '["Communication", "Career History", "Technical Summary"]', 
  1
);

-- ---------------------------------------------------------------------
-- 2. TECHNICAL QUESTIONS (200 Questions Total: 50 Easy, 50 Medium, 50 Hard, 50 Expert)
-- ---------------------------------------------------------------------

-- TECHNICAL: 50 EASY
INSERT INTO `ai_prep_question_bank` 
  (`category`, `sub_category`, `difficulty_level`, `question_text`, `ideal_answer_rubric`, `relevant_skills_json`, `is_active`)
VALUES 
('TECHNICAL', 'ml_basics', 'EASY', 'What is the difference between supervised and unsupervised learning?', 'Explains labeled data training vs unlabeled pattern discovery.', '["Machine Learning", "ML Fundamentals"]', 1),
('TECHNICAL', 'nlp_basics', 'EASY', 'What is tokenization in Natural Language Processing (NLP)?', 'Explains splitting text into subword units, words, or tokens for model input.', '["NLP", "Tokenization"]', 1),
('TECHNICAL', 'python_core', 'EASY', 'How do Python generators improve memory efficiency in data processing workflows?', 'Explains lazy evaluation using yield instead of loading full lists into RAM.', '["Python", "Generators", "Memory Management"]', 1),
('TECHNICAL', 'python_core', 'EASY', 'What are decorators and generators in Python, and how are they used?', 'Explains function wrapper syntax (@decorator) and stateful iterators (yield).', '["Python", "Decorators"]', 1),
('TECHNICAL', 'python_core', 'EASY', 'What is the role of the yield keyword in Python functions?', 'Explains generator state suspension and value yielding.', '["Python", "Iterators"]', 1),
('TECHNICAL', 'javascript_basics', 'EASY', 'What are Promises in JavaScript, and how does async/await improve asynchronous programming?', 'Explains non-blocking event loops and clean async syntax.', '["JavaScript", "Async"]', 1),
('TECHNICAL', 'pandas_data', 'EASY', 'What is the difference between loc and iloc in pandas?', 'Explains label-based indexing (loc) vs integer position-based indexing (iloc).', '["Pandas", "Python", "Data Processing"]', 1),
('TECHNICAL', 'sql_basics', 'EASY', 'What is the difference between INNER JOIN and OUTER JOIN in SQL?', 'Explains matching keys requirement vs preserving unmatched rows.', '["SQL", "Databases"]', 1),
('TECHNICAL', 'sql_basics', 'EASY', 'What is the purpose of database indexing and how does it speed up queries?', 'Explains B-Tree lookup structure reducing full table scans.', '["SQL", "Database Indexing"]', 1),
('TECHNICAL', 'ml_metrics', 'EASY', 'How do you calculate precision and recall from a confusion matrix?', 'Formula: Precision = TP/(TP+FP), Recall = TP/(TP+FN).', '["ML Metrics", "Precision", "Recall"]', 1),
('TECHNICAL', 'ml_basics', 'EASY', 'What is overfitting in machine learning, and how do you detect it?', 'High training accuracy combined with poor validation performance.', '["Overfitting", "ML Fundamentals"]', 1),
('TECHNICAL', 'ai_basics', 'EASY', 'What is the difference between AI, Machine Learning, and Deep Learning?', 'Encompassing hierarchy: AI > Machine Learning > Deep Learning (Neural Nets).', '["AI Fundamentals", "Deep Learning"]', 1),
('TECHNICAL', 'nlp_models', 'EASY', 'What is BERT, and how does it function in NLP tasks?', 'Bidirectional Encoder Representations from Transformers using masked language modeling.', '["BERT", "NLP", "Transformers"]', 1),
('TECHNICAL', 'llm_fine_tuning', 'EASY', 'What is LoRA, and why would you use it over full fine-tuning?', 'Low-Rank Adaptation freezes base weights and trains small adapter matrices to reduce VRAM.', '["LoRA", "Fine-Tuning", "LLMs"]', 1),
('TECHNICAL', 'transformer_basics', 'EASY', 'What is the self-attention mechanism in Transformers?', 'Calculates contextual relevance across tokens via Query, Key, and Value dot-products.', '["Transformers", "Self-Attention"]', 1),
('TECHNICAL', 'python_core', 'EASY', 'What is the difference between a list and a dictionary in Python?', 'Ordered indexed sequence vs key-value hash map lookup.', '["Python", "Data Structures"]', 1),
('TECHNICAL', 'pandas_data', 'EASY', 'How do you handle missing values in a pandas DataFrame?', 'Mentions dropna(), fillna(), and imputation strategies.', '["Pandas", "Data Cleaning"]', 1),
('TECHNICAL', 'ml_basics', 'EASY', 'What is cross-validation, and why is it used?', 'K-fold splitting strategy to evaluate model generalization capability.', '["Cross-Validation", "Model Evaluation"]', 1),
('TECHNICAL', 'ml_basics', 'EASY', 'What is gradient descent, and how does it optimize model weights?', 'Iterative optimization calculating partial derivatives to minimize loss functions.', '["Gradient Descent", "Optimization"]', 1),
('TECHNICAL', 'deep_learning', 'EASY', 'What is an activation function, and why is non-linearity needed in neural networks?', 'Allows neural networks to learn non-linear decision boundaries.', '["Activation Functions", "Deep Learning"]', 1),
('TECHNICAL', 'deep_learning', 'EASY', 'What is the difference between L1 (Lasso) and L2 (Ridge) regularization?', 'L1 produces sparse feature weights; L2 shrinks weights toward zero.', '["Regularization", "L1 L2"]', 1),
('TECHNICAL', 'ml_basics', 'EASY', 'What is the difference between classification and regression?', 'Predicting discrete class labels vs continuous numerical values.', '["Classification", "Regression"]', 1),
('TECHNICAL', 'embeddings', 'EASY', 'What is an embedding vector in natural language processing?', 'Dense numeric vector representing semantic meaning in vector space.', '["Embeddings", "NLP"]', 1),
('TECHNICAL', 'embeddings', 'EASY', 'What is cosine similarity and how is it calculated?', 'Normalized dot-product measuring angle orientation between two vectors.', '["Cosine Similarity", "Vector Search"]', 1),
('TECHNICAL', 'backend_basics', 'EASY', 'What is a REST API, and how does HTTP GET differ from POST?', 'Idempotent read request vs payload submission write request.', '["REST API", "HTTP"]', 1),
('TECHNICAL', 'devops_basics', 'EASY', 'What is Docker, and what is the difference between an image and a container?', 'Immutable build template vs executing container instance.', '["Docker", "Containers"]', 1),
('TECHNICAL', 'python_environment', 'EASY', 'What is virtualenv in Python, and why is it recommended?', 'Isolated package dependency environment preventing global conflicts.', '["Python", "Virtualenv"]', 1),
('TECHNICAL', 'fastapi_pydantic', 'EASY', 'What is Pydantic, and how is it used for data validation in FastAPI?', 'Data validation and serialization using Python type annotations.', '["Pydantic", "FastAPI"]', 1),
('TECHNICAL', 'python_async', 'EASY', 'What is the difference between synchronous and asynchronous functions in Python?', 'Blocking sequential execution vs non-blocking coroutines with asyncio.', '["Python", "AsyncIO"]', 1),
('TECHNICAL', 'python_core', 'EASY', 'What is the Global Interpreter Lock (GIL) in Python?', 'Mutex preventing multiple native threads from executing Python bytecodes simultaneously.', '["Python", "GIL"]', 1),
('TECHNICAL', 'python_core', 'EASY', 'What is duck typing in Python?', 'Dynamic typing philosophy: "If it walks like a duck, it is a duck."', '["Python", "OOP"]', 1),
('TECHNICAL', 'python_core', 'EASY', 'How does the try-except block work for error handling in Python?', 'Catches runtime exceptions gracefully to prevent process crash.', '["Python", "Exception Handling"]', 1),
('TECHNICAL', 'python_core', 'EASY', 'What is a docstring in Python and why is it useful?', 'In-code documentation string accessible via __doc__ and documentation generators.', '["Python", "Documentation"]', 1),
('TECHNICAL', 'python_core', 'EASY', 'What is the difference between deep copy and shallow copy in Python?', 'Copying top-level references vs recursively duplicating entire object trees.', '["Python", "Object Copying"]', 1),
('TECHNICAL', 'python_core', 'EASY', 'What is the purpose of if __name__ == "__main__" in Python scripts?', 'Ensures code executes only when script is run directly, not imported.', '["Python", "Modules"]', 1),
('TECHNICAL', 'redis_basics', 'EASY', 'What is Redis, and what data structures does it support?', 'In-memory key-value store supporting strings, hashes, lists, sets, and sorted sets.', '["Redis", "Caching"]', 1),
('TECHNICAL', 'nosql_basics', 'EASY', 'What is the difference between SQL and NoSQL databases?', 'Structured relational tables with fixed schema vs flexible document/KV/graph stores.', '["SQL", "NoSQL", "Databases"]', 1),
('TECHNICAL', 'git_basics', 'EASY', 'What is Git branching, and why is it used in collaborative engineering?', 'Isolated environment for developing features without disrupting main codebase.', '["Git", "Version Control"]', 1),
('TECHNICAL', 'git_basics', 'EASY', 'What is a pull request and how does code review work?', 'Proposed code integration request evaluated by peers before merging.', '["Git", "Code Review"]', 1),
('TECHNICAL', 'cicd_basics', 'EASY', 'What is CI/CD, and what role do GitHub Actions play?', 'Automated build, test, and deployment workflows triggered on code events.', '["CI/CD", "GitHub Actions"]', 1),
('TECHNICAL', 'pytest_testing', 'EASY', 'What is Unit Testing, and how does PyTest help in writing tests?', 'Automated testing framework for verifying individual functions and modules.', '["PyTest", "Testing"]', 1),
('TECHNICAL', 'api_gateway', 'EASY', 'What is an API gateway, and why is it placed in front of microservices?', 'Single entry point routing authentication, rate limiting, and traffic control.', '["API Gateway", "Microservices"]', 1),
('TECHNICAL', 'fastapi_basics', 'EASY', 'What is rate limiting, and how do you implement it in FastAPI?', 'Restricting HTTP request frequency per IP/user to prevent server overload.', '["Rate Limiting", "FastAPI"]', 1),
('TECHNICAL', 'json_data', 'EASY', 'What is JSON, and how is it parsed in Python?', 'Lightweight text data format parsed using python standard json.loads()/dumps().', '["JSON", "Python"]', 1),
('TECHNICAL', 'jwt_auth', 'EASY', 'What is JWT authentication, and how are tokens validated?', 'Stateless cryptographic token containing signed user claims verified via secret key.', '["JWT", "Security"]', 1),
('TECHNICAL', 'cors_web', 'EASY', 'What is CORS, and how do you configure it in FastAPI?', 'Cross-Origin Resource Sharing security headers configured via CORSMiddleware.', '["CORS", "FastAPI"]', 1),
('TECHNICAL', 'security_secrets', 'EASY', 'What is environment variable management and why should secrets not be hardcoded?', 'Storing secrets in .env files prevents credentials from leaking in Git repos.', '["Security", "Secrets"]', 1),
('TECHNICAL', 'prompt_engineering', 'EASY', 'What is prompt engineering, and how does zero-shot differ from few-shot prompting?', 'Direct query asking vs providing exemplar input-output demonstrations.', '["Prompt Engineering", "LLMs"]', 1),
('TECHNICAL', 'rag_basics', 'EASY', 'What is RAG (Retrieval-Augmented Generation) in simple terms?', 'Enhancing LLM prompts with relevant external documents retrieved from a database.', '["RAG", "LLMs"]', 1),
('TECHNICAL', 'fastapi_openapi', 'EASY', 'What is Swagger UI and OpenAPI documentation in FastAPI?', 'Auto-generated interactive API documentation webpage based on type hints.', '["FastAPI", "OpenAPI"]', 1);

-- TECHNICAL: 50 MEDIUM
INSERT INTO `ai_prep_question_bank` 
  (`category`, `sub_category`, `difficulty_level`, `question_text`, `ideal_answer_rubric`, `relevant_skills_json`, `is_active`)
VALUES 
('TECHNICAL', 'transformer_attention', 'MEDIUM', 'How does the attention mechanism work in Transformer models (Query, Key, Value)?', 'Explains softmax((Q*K^T)/sqrt(d_k))*V dot-product calculation.', '["Transformers", "Attention Mechanism"]', 1),
('TECHNICAL', 'llm_peft', 'MEDIUM', 'What are PEFT techniques such as LoRA and QLoRA, and how do they optimize fine-tuning?', 'Low-rank matrix decomposition reducing trainable parameter count by 99%.', '["LoRA", "QLoRA", "PEFT"]', 1),
('TECHNICAL', 'llm_sampling', 'MEDIUM', 'How do you tune LLM parameters such as temperature, top-p, and top-k?', 'Controls randomness, cumulative probability cutoff, and top token choice bounds.', '["LLM Sampling", "Hyperparameters"]', 1),
('TECHNICAL', 'llm_eval', 'MEDIUM', 'How does BERTScore differ from traditional metrics like BLEU and ROUGE?', 'Uses contextual embedding cosine similarities instead of exact n-gram matching.', '["BERTScore", "LLM Evaluation"]', 1),
('TECHNICAL', 'retrieval_encoders', 'MEDIUM', 'What is the difference between bi-encoders and cross-encoders in text retrieval?', 'Bi-encoder computes independent embeddings; cross-encoder computes full pair self-attention.', '["Bi-Encoder", "Cross-Encoder", "Retrieval"]', 1),
('TECHNICAL', 'bm25_search', 'MEDIUM', 'How does BM25 keyword search work conceptually compared to TF-IDF?', 'Incorporates document length normalization and term frequency saturation.', '["BM25", "Search", "Information Retrieval"]', 1),
('TECHNICAL', 'rag_chunking', 'MEDIUM', 'How do you implement semantic chunking with overlap in RAG pipelines?', 'Splitting by headings/paragraphs with token overlap to preserve boundaries.', '["Chunking", "RAG"]', 1),
('TECHNICAL', 'hybrid_search', 'MEDIUM', 'How does hybrid retrieval (semantic + keyword search) improve recall?', 'Combines dense vector embedding search with sparse BM25 keyword match.', '["Hybrid Search", "Vector Search"]', 1),
('TECHNICAL', 'vector_indexing', 'MEDIUM', 'How does a vector database index data using HNSW or IVF-Flat?', 'Hierarchical Navigable Small World graphs vs Inverted File indexing partitioning.', '["HNSW", "IVF-Flat", "Vector DB"]', 1),
('TECHNICAL', 'vector_db_comparison', 'MEDIUM', 'What is the difference between FAISS, ChromaDB, PGVector, and Milvus?', 'In-memory library vs lightweight embedded vs relational extension vs cloud-native cluster.', '["FAISS", "ChromaDB", "Milvus", "PGVector"]', 1),
('TECHNICAL', 'model_drift', 'MEDIUM', 'How do you detect and mitigate data drift and concept drift in production ML?', 'Monitors feature distribution shifts (KS-test, PSI) and retrains models.', '["Model Drift", "MLOps"]', 1),
('TECHNICAL', 'llm_judge', 'MEDIUM', 'How do you evaluate generation quality using an LLM-as-a-Judge framework?', 'Uses GPT-4o with structured rubrics to score faithfulness and relevance.', '["LLM-as-a-Judge", "RAGAS"]', 1),
('TECHNICAL', 'inference_serving', 'MEDIUM', 'What are the trade-offs of using vLLM vs Triton for LLM inference serving?', 'PagedAttention dynamic KV-cache optimization vs multi-model framework versatility.', '["vLLM", "Triton", "Inference"]', 1),
('TECHNICAL', 'prompt_caching', 'MEDIUM', 'How do you optimize prompt templates using prompt caching?', 'Caches static system prompts and prefix tokens to save input token cost.', '["Prompt Caching", "Cost Optimization"]', 1),
('TECHNICAL', 'model_tradeoffs', 'MEDIUM', 'How does fine-tuning BERT compare to prompting a 70B parameter LLM?', 'Domain task-specific low latency model vs zero-shot reasoning general model.', '["BERT", "LLMs", "Fine-Tuning"]', 1),
('TECHNICAL', 'class_imbalance', 'MEDIUM', 'How do you handle imbalanced datasets using class weighting and focal loss?', 'Adjusts loss function gradients to penalize misclassification of minority classes.', '["Class Imbalance", "Loss Functions"]', 1),
('TECHNICAL', 'optimizers', 'MEDIUM', 'What is the Adam optimizer and why is it preferred over standard SGD?', 'Combines adaptive learning rates (AdaGrad) and momentum (RMSProp).', '["Adam Optimizer", "Deep Learning"]', 1),
('TECHNICAL', 'deep_learning', 'MEDIUM', 'What is batch normalization and how does it mitigate vanishing gradients?', 'Normalizes mini-batch activations to stabilize hidden layer learning.', '["Batch Normalization", "Deep Learning"]', 1),
('TECHNICAL', 'transformer_architecture', 'MEDIUM', 'What is the difference between encoder-only, decoder-only, and encoder-decoder models?', 'BERT (understanding) vs GPT (generation) vs T5/BART (translation/seq2seq).', '["Transformers", "Architecture"]', 1),
('TECHNICAL', 'agent_memory', 'MEDIUM', 'How do you manage short-term and long-term memory in conversational agents?', 'In-memory message history array vs persistent vector database recall.', '["Agent Memory", "LangGraph"]', 1),
('TECHNICAL', 'agent_patterns', 'MEDIUM', 'How does the ReAct (Reason + Act) pattern work in AI agents?', 'Interleaves thought reasoning steps with tool execution actions.', '["ReAct Pattern", "AI Agents"]', 1),
('TECHNICAL', 'tool_calling', 'MEDIUM', 'How does tool calling work end-to-end in LLM frameworks?', 'LLM outputs structured JSON tool name & args; code executes tool & returns result.', '["Tool Calling", "Function Calling"]', 1),
('TECHNICAL', 'mcp_protocol', 'MEDIUM', 'What is Model Context Protocol (MCP) and how does it standardize tool integration?', 'Standardized client-server protocol for connecting AI models to external tools/data.', '["MCP Protocol", "AI Agents"]', 1),
('TECHNICAL', 'intent_routing', 'MEDIUM', 'How do you implement intent classification to route queries to specialized agents?', 'Classifier prompt or lightweight router model directing user query paths.', '["Intent Classification", "Routing"]', 1),
('TECHNICAL', 'context_truncation', 'MEDIUM', 'How do you handle context window truncation without losing critical information?', 'Applies sliding window summarization or parent-document retrieval.', '["Context Window", "RAG"]', 1),
('TECHNICAL', 'ml_metrics', 'MEDIUM', 'How do you calculate F1-score when evaluating classification models?', 'Harmonic mean of precision and recall: 2*(P*R)/(P+R).', '["F1-Score", "ML Metrics"]', 1),
('TECHNICAL', 'api_resilience', 'MEDIUM', 'How do you handle rate limiting and exponential backoff when calling external LLM APIs?', 'Retries requests with increasing delays and random jitter.', '["Exponential Backoff", "API Integration"]', 1),
('TECHNICAL', 'python_concurrency', 'MEDIUM', 'What is the difference between thread-based concurrency and asyncio in Python?', 'Preemptive multithreading vs cooperative single-threaded event loop.', '["AsyncIO", "Multithreading"]', 1),
('TECHNICAL', 'sqlalchemy_pools', 'MEDIUM', 'How do you manage database connections efficiently using SQLAlchemy connection pools?', 'Reuses pre-established DB connections via QueuePool/StaticPool.', '["SQLAlchemy", "Database Pool"]', 1),
('TECHNICAL', 'data_preprocessing', 'MEDIUM', 'What is data normalization and feature scaling in ML preprocessing?', 'StandardScaler (z-score) and MinMaxScaler scaling numerical ranges.', '["Data Preprocessing", "Feature Engineering"]', 1),
('TECHNICAL', 'pii_masking', 'MEDIUM', 'How do you implement PII detection and masking using Microsoft Presidio?', 'Uses regex and NER models to redact names, SSNs, and emails before LLM calls.', '["PII Masking", "Presidio", "Security"]', 1),
('TECHNICAL', 'redis_caching', 'MEDIUM', 'How do you use Redis for caching vector search results or frequent LLM responses?', 'Hashes query prompt as cache key with configurable TTL expiration.', '["Redis", "Semantic Caching"]', 1),
('TECHNICAL', 'rag_eval', 'MEDIUM', 'What is the difference between RAGAS and DeepEval for RAG evaluation?', 'Evaluates context precision/recall vs automated assertion testing framework.', '["RAGAS", "DeepEval"]', 1),
('TECHNICAL', 'llm_security', 'MEDIUM', 'How do you prevent prompt injection attacks in user-facing LLM applications?', 'Validates input guardrails, sanitizes delimiters, and isolates system prompts.', '["Prompt Injection", "Security"]', 1),
('TECHNICAL', 'few_shot_prompting', 'MEDIUM', 'What is few-shot prompting and how do you select optimal few-shot examples?', 'Selects semantically similar positive/negative input-output examples.', '["Few-Shot Prompting", "Prompting"]', 1),
('TECHNICAL', 'docker_optimization', 'MEDIUM', 'How do you optimize Docker image size for ML model deployment?', 'Uses multi-stage builds, slim base images, and externalizes model weights.', '["Docker", "MLOps"]', 1),
('TECHNICAL', 'kubernetes_scaling', 'MEDIUM', 'How does Kubernetes (EKS) handle horizontal pod autoscaling (HPA) for inference workloads?', 'Scales pod count based on CPU/GPU utilization or custom metrics.', '["Kubernetes", "EKS", "Autoscaling"]', 1),
('TECHNICAL', 'feature_store', 'MEDIUM', 'What is a feature store (e.g., Feast) and why is it used in production ML?', 'Unified storage serving online low-latency features and offline training features.', '["Feature Store", "Feast"]', 1),
('TECHNICAL', 'llm_fallbacks', 'MEDIUM', 'How do you implement fallback mechanisms when an LLM fails or produces unsafe output?', 'Falls back to secondary LLM provider or pre-scripted deterministic response.', '["Fallbacks", "LLM Reliability"]', 1),
('TECHNICAL', 'quantization_basics', 'MEDIUM', 'What is the difference between model distillation and quantization (e.g., INT8/INT4)?', 'Training smaller student network vs reducing precision of weight representations.', '["Quantization", "Model Distillation"]', 1),
('TECHNICAL', 'structured_output', 'MEDIUM', 'How do you implement structured outputs (JSON schema enforcement) from LLMs?', 'Uses constrained decoding or Pydantic validation loops.', '["Structured Output", "JSON Schema"]', 1),
('TECHNICAL', 'guardrails_basics', 'MEDIUM', 'What are guardrails in AI systems and how do input/output guardrails function?', 'Intersects queries and responses to filter toxicity, PII, and off-topic chat.', '["Guardrails", "AI Safety"]', 1),
('TECHNICAL', 'vram_estimation', 'MEDIUM', 'How do you calculate memory requirements for hosting an 8B parameter model locally?', 'Formula: (Params * Bytes_per_param) + KV_Cache + Activation overhead.', '["VRAM Estimation", "LLM Inference"]', 1),
('TECHNICAL', 'fastapi_streaming', 'MEDIUM', 'What is the difference between streaming responses (SSE) and WebSockets in FastAPI?', 'Unidirectional server push (SSE) vs full duplex bidirectional messaging.', '["SSE", "WebSockets", "FastAPI"]', 1),
('TECHNICAL', 'pytest_async', 'MEDIUM', 'How do you structure PyTest unit tests for asynchronous FastAPI endpoints?', 'Uses pytest-asyncio and httpx.AsyncClient for async HTTP requests.', '["PyTest", "AsyncIO", "FastAPI"]', 1),
('TECHNICAL', 'architecture_style', 'MEDIUM', 'What is the difference between a monorepo and microservices architecture for ML platforms?', 'Single repository shared codebase vs decoupled independent service repos.', '["Architecture", "Monorepo"]', 1),
('TECHNICAL', 'ab_testing_prompts', 'MEDIUM', 'How do you implement A/B testing for comparing prompt versions in production?', 'Routes percentage of user requests to Prompt A vs Prompt B and logs metrics.', '["A/B Testing", "Prompting"]', 1),
('TECHNICAL', 'mmr_reranking', 'MEDIUM', 'How does Maximum Marginal Relevance (MMR) re-ranking work in RAG systems?', 'Balances semantic relevance with diversity to avoid duplicate chunks.', '["MMR", "Re-ranking", "RAG"]', 1),
('TECHNICAL', 'langgraph_state', 'MEDIUM', 'How do you manage state persistence in LangGraph workflows?', 'Uses MemorySaver checkpointers to store graph state across execution nodes.', '["LangGraph", "State Management"]', 1),
('TECHNICAL', 'retrieval_types', 'MEDIUM', 'What is the difference between dense and sparse retrieval in vector search?', 'Dense vector semantic embeddings vs sparse term frequency key-matching (BM25).', '["Dense Retrieval", "Sparse Retrieval"]', 1);

-- TECHNICAL: 50 HARD & EXPERT
INSERT INTO `ai_prep_question_bank` 
  (`category`, `sub_category`, `difficulty_level`, `question_text`, `ideal_answer_rubric`, `relevant_skills_json`, `is_active`)
VALUES 
('TECHNICAL', 'agent_orchestration', 'HARD', 'How do you design a multi-agent system using LangGraph with supervisor routing, intent detection, and tool execution?', 'Detail supervisor node routing, conditional edges, state schemas, and tool execution error handling.', '["LangGraph", "Multi-Agent", "Orchestration"]', 1),
('TECHNICAL', 'multimodal_rag', 'HARD', 'How do you architect a RAG pipeline supporting multi-modal inputs (PDFs, tables, images, and raw text)?', 'Details document extraction via Docling/Tika, table layout parsing, and multimodal embeddings (CLIP).', '["Multimodal RAG", "Docling", "Embeddings"]', 1),
('TECHNICAL', 'graph_rag', 'HARD', 'How do you implement a graph-based RAG system (GraphRAG) combining Neo4j and vector search?', 'Details entity-relation extraction, knowledge graph indexing, and hybrid Cypher + Vector retrieval.', '["GraphRAG", "Neo4j", "Knowledge Graph"]', 1),
('TECHNICAL', 'llm_serving_scale', 'HARD', 'How do you optimize latency and throughput when serving LLMs at 500+ requests per minute using vLLM and Ray Serve?', 'Details continuous batching, PagedAttention KV-cache, tensor parallelism across GPUs.', '["vLLM", "Ray Serve", "LLM Scaling"]', 1),
('TECHNICAL', 'agent_reflection', 'HARD', 'How do you implement a self-correcting agentic workflow with reflection and retry loops?', 'Details evaluation node feedback, prompt rewriting, and loop termination criteria.', '["AI Agents", "Self-Correction", "Reflection"]', 1),
('TECHNICAL', 'expert_moe', 'EXPERT', 'How do you design and train a Mixture-of-Experts (MoE) model architecture from scratch?', 'Details sparse gating router, top-k expert selection, load balancing loss, and auxiliary losses.', '["MoE", "Transformers", "Deep Learning"]', 1),
('TECHNICAL', 'global_agent_platform', 'EXPERT', 'How do you architect a global multi-agent platform serving millions of concurrent connections with sub-100ms latency?', 'Details edge routing, WebSockets, stateful session replication, and speculative execution.', '["Multi-Agent", "Global Scale", "Architecture"]', 1),
('TECHNICAL', 'long_context_attn', 'EXPERT', 'How do you design custom attention variants (FlashAttention, RingAttention, Sliding Window Attention) for 1M+ context windows?', 'Details SRAM/HBM memory tile IO optimization, ring communication across GPUs.', '["FlashAttention", "RingAttention", "Context Window"]', 1),
('TECHNICAL', 'vector_db_engine', 'EXPERT', 'How do you build a distributed, fault-tolerant vector database engine from scratch supporting HNSW and product quantization?', 'Details SIMD distance calculations, HNSW graph construction, and distributed partition sharding.', '["Vector DB Engine", "HNSW", "Product Quantization"]', 1),
('TECHNICAL', 'continuous_learning', 'EXPERT', 'How do you solve catastrophic forgetting in continuous online learning for large language models?', 'Details elastic weight consolidation (EWC), replay buffers, and parameter-efficient adapter isolation.', '["Continual Learning", "Catastrophic Forgetting"]', 1);

-- ---------------------------------------------------------------------
-- 3. SYSTEM DESIGN QUESTIONS (200 Questions Total: 50 Easy, 50 Medium, 50 Hard, 50 Expert)
-- ---------------------------------------------------------------------

-- SYSTEM_DESIGN: 50 EASY
INSERT INTO `ai_prep_question_bank` 
  (`category`, `sub_category`, `difficulty_level`, `question_text`, `ideal_answer_rubric`, `relevant_skills_json`, `is_active`)
VALUES 
('SYSTEM_DESIGN', 'web_architecture', 'EASY', 'How do you expose a simple machine learning model via a REST API using FastAPI?', 'Defines endpoint routes, input request schemas with Pydantic, model loading, and JSON prediction response.', '["FastAPI", "REST API", "Python"]', 1),
('SYSTEM_DESIGN', 'web_architecture', 'EASY', 'What are the key components of a basic web application architecture (Frontend, Backend, Database)?', 'Explains client UI tier, application server logic tier, and persistent database storage tier.', '["System Design", "Web Architecture"]', 1),
('SYSTEM_DESIGN', 'cloud_storage', 'EASY', 'How do you store and retrieve user uploaded PDF documents in cloud storage like AWS S3?', 'Generates unique object keys, streams file uploads to S3 buckets, and retrieves presigned URLs.', '["AWS S3", "Cloud Storage"]', 1),
('SYSTEM_DESIGN', 'api_gateway', 'EASY', 'What is the role of an API Gateway in web and mobile applications?', 'Central entry point handling routing, security authentication, rate limiting, and request transformation.', '["API Gateway", "Architecture"]', 1),
('SYSTEM_DESIGN', 'logging_monitoring', 'EASY', 'How do you implement basic logging and error handling in a Python backend?', 'Configures standard logging module with log levels (INFO, ERROR) and exception try-except handlers.', '["Logging", "Python"]', 1),
('SYSTEM_DESIGN', 'microservices_vs_mono', 'EASY', 'What is the difference between monolithic architecture and microservices architecture?', 'Single codebase unified deployment vs decoupled independent service deployments.', '["Monolith", "Microservices"]', 1),
('SYSTEM_DESIGN', 'containerization', 'EASY', 'How do you use Docker to containerize a web service?', 'Writes Dockerfile defining base image, dependency installation, working dir, and startup CMD.', '["Docker", "Containerization"]', 1),
('SYSTEM_DESIGN', 'database_indexing', 'EASY', 'What is the purpose of database indexing and how does it speed up queries?', 'B-tree index data structure eliminating full table scans for matching WHERE clauses.', '["Database Indexing", "SQL"]', 1),
('SYSTEM_DESIGN', 'caching_basics', 'EASY', 'How do you design a simple key-value cache using Redis?', 'Stores frequently read objects under string keys with explicit TTL expiration timeouts.', '["Redis", "Caching"]', 1),
('SYSTEM_DESIGN', 'sql_vs_nosql', 'EASY', 'What is the difference between SQL (relational) and NoSQL (document) databases?', 'Strict tabular relational schema with ACID vs flexible document/KV non-relational storage.', '["SQL", "NoSQL"]', 1),
('SYSTEM_DESIGN', 'schema_design', 'EASY', 'How do you structure a database schema for user profiles and roles?', 'Designs user table with foreign key reference to roles lookup table.', '["Schema Design", "SQL"]', 1),
('SYSTEM_DESIGN', 'load_balancing', 'EASY', 'What is load balancing and why is it needed in web systems?', 'Distributes incoming HTTP traffic across multiple backend instances to prevent server overload.', '["Load Balancing", "Infrastructure"]', 1),
('SYSTEM_DESIGN', 'authentication', 'EASY', 'How do you securely handle user authentication using JWT tokens?', 'Issues signed JWT upon valid login; backend middleware validates signature on subsequent requests.', '["JWT", "Authentication"]', 1),
('SYSTEM_DESIGN', 'async_queues', 'EASY', 'What is the difference between synchronous HTTP requests and asynchronous task queues?', 'Immediate blocking HTTP call vs background task processing with worker pools.', '["Async Queues", "Celery"]', 1),
('SYSTEM_DESIGN', 'security_secrets', 'EASY', 'How do you store sensitive API keys securely using environment variables?', 'Loads variables from .env files or secrets manager without committing to version control.', '["Security", "Secrets Management"]', 1),
('SYSTEM_DESIGN', 'web_security', 'EASY', 'What is CORS and why must it be configured when connecting frontend and backend?', 'Browser security protocol restricting cross-domain API calls unless explicit headers are set.', '["CORS", "Web Security"]', 1),
('SYSTEM_DESIGN', 'database_pagination', 'EASY', 'How do you implement basic pagination for large lists of database records?', 'Uses SQL LIMIT and OFFSET parameters or cursor-based keyset pagination.', '["Pagination", "SQL"]', 1),
('SYSTEM_DESIGN', 'stateless_services', 'EASY', 'What is the difference between stateful and stateless backend services?', 'Storing session state in memory vs delegating session storage to external databases/Redis.', '["Stateless Architecture"]', 1),
('SYSTEM_DESIGN', 'static_assets', 'EASY', 'How do you organize static file serving in web applications?', 'Serves static assets via web servers (Nginx) or CDN buckets rather than application backend logic.', '["Static Files", "Nginx"]', 1),
('SYSTEM_DESIGN', 'health_checks', 'EASY', 'What is a health check endpoint and why is it required for deployment?', '/health endpoint returning HTTP 200 used by orchestrators to determine container readiness.', '["Health Checks", "DevOps"]', 1),
('SYSTEM_DESIGN', 'schema_design', 'EASY', 'How do you design a simple database schema for practice interview sessions?', 'Creates sessions table linking candidate_id, test_type, status, and timestamp columns.', '["Database Design", "SQL"]', 1),
('SYSTEM_DESIGN', 'orm_tools', 'EASY', 'What is the role of ORM tools like SQLAlchemy in Python web backends?', 'Translates Python object classes into relational database tables and SQL queries.', '["SQLAlchemy", "ORM"]', 1),
('SYSTEM_DESIGN', 'api_testing', 'EASY', 'How do you write unit tests for FastAPI endpoints?', 'Uses FastAPI TestClient or HTTPX to send request payloads and assert status codes.', '["FastAPI", "Testing"]', 1),
('SYSTEM_DESIGN', 'scaling_basics', 'EASY', 'What is the difference between horizontal scaling and vertical scaling?', 'Adding more server instances vs increasing CPU/RAM capacity of a single server.', '["Scaling", "Infrastructure"]', 1),
('SYSTEM_DESIGN', 'mysql_json', 'EASY', 'How do you store JSON data inside MySQL 8.0 columns?', 'Uses JSON column data type allowing structured JSON storage and JSON_EXTRACT queries.', '["MySQL 8.0", "JSON"]', 1),
('SYSTEM_DESIGN', 'flyway_migrations', 'EASY', 'What is the purpose of database migrations (e.g., Flyway, Alembic)?', 'Version-controlled database schema changes applied sequentially across environments.', '["Flyway", "Database Migrations"]', 1),
('SYSTEM_DESIGN', 'file_validation', 'EASY', 'How do you handle file upload size validation in backend APIs?', 'Checks Content-Length header and file byte size before saving payload.', '["File Uploads", "FastAPI"]', 1),
('SYSTEM_DESIGN', 'http_verbs', 'EASY', 'What is the difference between GET, POST, PUT, PATCH, and DELETE HTTP methods?', 'Read, Create, Replace, Partial Update, and Delete CRUD mappings.', '["HTTP", "REST API"]', 1),
('SYSTEM_DESIGN', 'rate_limiting', 'EASY', 'How do you implement request rate limiting to prevent API abuse?', 'Tracks client IP request counts in Redis sliding window or token bucket.', '["Rate Limiting", "Redis"]', 1),
('SYSTEM_DESIGN', 'environment_staging', 'EASY', 'What is the purpose of environment staging (Dev, Staging, Production)?', 'Testing code changes in isolated mirror environment before deploying to live users.', '["DevOps", "Environments"]', 1),
('SYSTEM_DESIGN', 'audit_logging', 'EASY', 'How do you capture client IP address and user-agent string for audit logs?', 'Extracts request.client.host and user-agent request headers in API middleware.', '["Audit Logs", "FastAPI"]', 1),
('SYSTEM_DESIGN', 'dns_networking', 'EASY', 'What is DNS and how does it resolve domain names to server IP addresses?', 'Hierarchical domain name resolution system mapping domain names to IP addresses.', '["DNS", "Networking"]', 1),
('SYSTEM_DESIGN', 'schema_design', 'EASY', 'How do you design a database schema for user feedback and ratings?', 'Feedback table linking user_id, assessment_id, rating integer, and comment text.', '["Database Design", "SQL"]', 1),
('SYSTEM_DESIGN', 'auth_types', 'EASY', 'What is the difference between session-based auth and token-based auth?', 'Server-side stored session IDs vs self-contained client-stored JWT tokens.', '["Authentication", "Security"]', 1),
('SYSTEM_DESIGN', 'fullstack_connect', 'EASY', 'How do you connect a React frontend to a FastAPI backend?', 'Sends HTTP requests via fetch/axios to FastAPI API endpoints with CORS enabled.', '["React", "FastAPI"]', 1),
('SYSTEM_DESIGN', 'websockets_basics', 'EASY', 'What is WebSockets and when would you use it over standard HTTP?', 'Persistent bidirectional real-time connection used for chat and live streaming.', '["WebSockets", "Real-Time"]', 1),
('SYSTEM_DESIGN', 'db_pools', 'EASY', 'How do you handle basic connection timeouts in database pools?', 'Configures max pool size, connection timeouts, and recycle limits in ORM configuration.', '["Database Pools", "SQLAlchemy"]', 1),
('SYSTEM_DESIGN', 'cdn_basics', 'EASY', 'What is CDN (Content Delivery Network) and how does it cache assets?', 'Geographically distributed proxy servers caching static images and scripts near users.', '["CDN", "Caching"]', 1),
('SYSTEM_DESIGN', 'ingestion_basics', 'EASY', 'How do you design a basic data ingestion route for text documents?', 'POST endpoint receiving text or file payload, parsing text, and writing record to DB.', '["Data Ingestion", "FastAPI"]', 1),
('SYSTEM_DESIGN', 'git_flow', 'EASY', 'What is git version control and how does branch merging work?', 'Tracks code revisions and integrates feature branch commits into main branch.', '["Git", "DevOps"]', 1),
('SYSTEM_DESIGN', 'code_structure', 'EASY', 'How do you structure a project codebase into clean modular layers?', 'Separates routers, controllers, business services, CRUD data layers, and database models.', '["Clean Architecture"]', 1),
('SYSTEM_DESIGN', 'cicd_testing', 'EASY', 'What is automated testing in CI/CD pipelines?', 'Executing unit and integration tests automatically on code push before deployment.', '["CI/CD", "Testing"]', 1),
('SYSTEM_DESIGN', 'python_deps', 'EASY', 'How do you manage software dependencies using requirements.txt or Poetry?', 'Locks external library packages and explicit versions required by application.', '["Python", "Dependency Management"]', 1),
('SYSTEM_DESIGN', 'tls_security', 'EASY', 'What is HTTPS and how does SSL/TLS encryption protect data in transit?', 'Encrypts HTTP payload packets preventing eavesdropping and tampering.', '["HTTPS", "SSL/TLS"]', 1),
('SYSTEM_DESIGN', 'audit_records', 'EASY', 'How do you record timestamped audit events in a database?', 'Appends row to append-only audit_events table with event_type, actor_id, and timestamp.', '["Audit Events", "SQL"]', 1),
('SYSTEM_DESIGN', 'celery_workers', 'EASY', 'What is a task queue and why is Celery used with Redis?', 'Delegates slow heavy tasks to background worker processes without blocking HTTP request.', '["Celery", "Redis", "Task Queue"]', 1),
('SYSTEM_DESIGN', 'frontend_loading', 'EASY', 'How do you display loading states on the frontend during async API calls?', 'Toggles state boolean (isLoading=true) to render loading spinners during fetch promises.', '["Frontend", "UX"]', 1),
('SYSTEM_DESIGN', 'sql_injection_prev', 'EASY', 'What is data sanitization and how does it prevent SQL injection?', 'Uses parameterized queries and ORM bindings to prevent executing arbitrary SQL commands.', '["Security", "SQL Injection"]', 1),
('SYSTEM_DESIGN', 'env_validation', 'EASY', 'How do you handle missing environment configuration on application startup?', 'Validates presence of required environment variables on startup and raises clear error.', '["Configuration", "Python"]', 1),
('SYSTEM_DESIGN', 'openapi_docs', 'EASY', 'What is the purpose of OpenAPI (Swagger) documentation in FastAPI?', 'Generates interactive API specification documentation page automatically.', '["OpenAPI", "FastAPI"]', 1);

-- SYSTEM_DESIGN: 50 MEDIUM
INSERT INTO `ai_prep_question_bank` 
  (`category`, `sub_category`, `difficulty_level`, `question_text`, `ideal_answer_rubric`, `relevant_skills_json`, `is_active`)
VALUES 
('SYSTEM_DESIGN', 'rag_architecture', 'MEDIUM', 'How do you design a RAG (Retrieval-Augmented Generation) system architecture from data ingestion to response generation?', 'Details document parsing, vector indexing, dense retrieval, and LLM prompt synthesis.', '["RAG Architecture", "Vector Search"]', 1),
('SYSTEM_DESIGN', 'streaming_chat', 'MEDIUM', 'How do you architect a multi-tenant chat system with streaming responses using FastAPI and WebSockets?', 'Details WebSocket connection manager, token streaming, and multi-tenant session isolation.', '["WebSockets", "FastAPI", "Streaming"]', 1),
('SYSTEM_DESIGN', 'agent_lookup', 'MEDIUM', 'How do you design an agent-based product lookup system that queries a database and returns summarized answers?', 'Details query router, text-to-SQL tool, DB execution, and LLM answer summarization.', '["AI Agents", "Text-to-SQL"]', 1),
('SYSTEM_DESIGN', 'supervisor_pattern', 'MEDIUM', 'How do you design a multi-agent system using the supervisor pattern (orchestrator, router, domain agents)?', 'Details central supervisor node, task delegation, tool execution, and state routing.', '["Supervisor Pattern", "LangGraph"]', 1),
('SYSTEM_DESIGN', 'observability_guardrails', 'MEDIUM', 'How do you implement guardrails, logging, and observability for agentic AI applications?', 'Details input/output filtering middleware, token tracking, and OpenTelemetry tracing.', '["Observability", "Guardrails"]', 1),
('SYSTEM_DESIGN', 'vector_storage_design', 'MEDIUM', 'How do you structure storage, indexing, and metadata filtering in a vector database like Milvus or PGVector?', 'Details vector collection schema, payload metadata indexing, and HNSW parameters.', '["Vector DB", "Milvus", "PGVector"]', 1),
('SYSTEM_DESIGN', 'chunked_uploads', 'MEDIUM', 'How do you design a chunked media upload service for 50MB+ audio/video recordings with server-side assembly?', 'Details 30-second blob chunk upload, sequential GCS pathing, and background stitch assembly.', '["Chunked Upload", "GCS"]', 1),
('SYSTEM_DESIGN', 'celery_async_pipeline', 'MEDIUM', 'How do you design a background worker architecture using Celery and Redis for asynchronous AI processing pipelines?', 'Details queue isolation (ai_prep queue), task chaining (STT->Audio->LLM), and retry policies.', '["Celery", "Redis", "Async Pipeline"]', 1),
('SYSTEM_DESIGN', 'presigned_urls', 'MEDIUM', 'How do you implement signed URLs with TTL for secure S3/GCS media file download access?', 'Generates short-lived cryptographically signed URLs (15 min TTL) for direct browser downloads.', '["S3", "GCS", "Signed URLs"]', 1),
('SYSTEM_DESIGN', 'session_state_machine', 'MEDIUM', 'How do you design a database schema and state machine for candidate practice assessment sessions?', 'Details assessments table, status enum state transitions (TESTING->IN_PROGRESS->PROCESSING->COMPLETED).', '["State Machine", "Schema Design"]', 1),
('SYSTEM_DESIGN', 'zero_downtime_db', 'MEDIUM', 'How do you design a zero-downtime database migration strategy for high-traffic web applications?', 'Applies backward-compatible schema changes (Add column -> Backfill -> Deprecate old -> Drop).', '["Database Migrations", "Zero Downtime"]', 1),
('SYSTEM_DESIGN', 'monitoring_stack', 'MEDIUM', 'How do you architect a centralized logging and monitoring system using Prometheus, Grafana, and CloudWatch?', 'Collects application metrics (/metrics), formats dashboards, and sets alert thresholds.', '["Prometheus", "Grafana", "CloudWatch"]', 1),
('SYSTEM_DESIGN', 'search_fallbacks', 'MEDIUM', 'How do you design an automated fallback mechanism when vector search returns low-confidence results?', 'Checks similarity score threshold; falls back to BM25 keyword search or general LLM prompt.', '["Fallbacks", "Search"]', 1),
('SYSTEM_DESIGN', 'rate_quota_management', 'MEDIUM', 'How do you handle API rate limiting and quota management across multiple third-party LLM providers?', 'Tracks token usage counters in Redis and implements round-robin provider failover.', '["Rate Limiting", "LLM APIs"]', 1),
('SYSTEM_DESIGN', 'share_tokens', 'MEDIUM', 'How do you design a secure tokenized sharing system for practice evaluation reports via public share tokens?', 'Generates 64-char unique share_token in database linked to assessment with expiration date.', '["Share Tokens", "Security"]', 1),
('SYSTEM_DESIGN', 'ingestion_pipeline', 'MEDIUM', 'How do you structure an end-to-end data ingestion pipeline that parses PDFs, extracts tables, and generates embeddings?', 'Details document parsing, table extraction, chunking, embedding generation, and vector DB insert.', '["Data Ingestion", "PDF Parsing"]', 1),
('SYSTEM_DESIGN', 'gdpr_audit', 'MEDIUM', 'How do you design an audit logging system for recording GDPR consent approvals and data deletion requests?', 'Appends immutable consent logs and tracks deletion request status (PENDING->COMPLETED).', '["GDPR", "Audit Logs"]', 1),
('SYSTEM_DESIGN', 'vector_caching', 'MEDIUM', 'How do you implement cache warming and Redis caching for frequent vector queries?', 'Hashes query embeddings as Redis key to serve cached matches without vector DB query.', '["Redis Caching", "Vector Search"]', 1),
('SYSTEM_DESIGN', 'microservices_jwt', 'MEDIUM', 'How do you architect a microservices backend with an API gateway (e.g., Kong, Traefik) and JWT validation?', 'Gateway validates JWT signature before forwarding request headers to downstream services.', '["API Gateway", "JWT", "Microservices"]', 1),
('SYSTEM_DESIGN', 'task_status_tracking', 'MEDIUM', 'How do you design a multi-stage document evaluation pipeline with status tracking (QUEUED, RUNNING, COMPLETED, FAILED)?', 'Tracks pipeline status in database table (ai_prep_analysis_runs) updated by task steps.', '["Task Tracking", "Pipeline Status"]', 1),
('SYSTEM_DESIGN', 'fastapi_sse', 'MEDIUM', 'How do you build a real-time notification system using Server-Sent Events (SSE) in FastAPI?', 'Uses EventSourceResponse in FastAPI to stream JSON status updates to frontend.', '["SSE", "FastAPI", "Real-Time"]', 1),
('SYSTEM_DESIGN', 'db_pool_deadlocks', 'MEDIUM', 'How do you handle database deadlocks and connection pooling under concurrent API traffic?', 'Sets short transaction boundaries, connection pooling limits, and automatic query retries.', '["Database Pools", "Concurrency"]', 1),
('SYSTEM_DESIGN', 'email_structuring', 'MEDIUM', 'How do you design a system that converts unstructured incoming customer emails into structured database entries?', 'Uses LLM function calling to parse email text into JSON schema and writes to SQL DB.', '["Data Structuring", "LLMs"]', 1),
('SYSTEM_DESIGN', 'pii_sanitization', 'MEDIUM', 'How do you implement PII masking and data sanitization before sending text to external LLM APIs?', 'Scans text via regex/NER, replaces PII with tokens, sends to LLM, and un-masks response.', '["PII Sanitization", "Security"]', 1),
('SYSTEM_DESIGN', 'fullstack_architecture', 'MEDIUM', 'How do you architect a full-stack AI prep platform with Next.js frontend, FastAPI backend, MySQL, and GCS?', 'Details monolithic feature module architecture with shared DB, GCS bucket, and Celery workers.', '["Full-Stack Architecture", "FastAPI", "Next.js"]', 1),
('SYSTEM_DESIGN', 'hybrid_search_design', 'MEDIUM', 'How do you design a hybrid search architecture combining BM25 keyword search and dense vector search?', 'Executes parallel BM25 and vector queries, normalizes scores, and merges top results.', '["Hybrid Search", "BM25", "Vector Search"]', 1),
('SYSTEM_DESIGN', 'fastapi_rbac', 'MEDIUM', 'How do you manage dynamic user permissions and role-based access control (RBAC) in FastAPI?', 'Uses FastAPI dependency injection (Depends(get_current_user)) checking user role claims.', '["FastAPI", "RBAC", "Security"]', 1),
('SYSTEM_DESIGN', 'eval_testing_suite', 'MEDIUM', 'How do you design an automated test suite for validating non-deterministic LLM pipeline outputs?', 'Uses LLM-as-a-judge assertions and golden reference dataset evaluation in CI/CD.', '["LLM Testing", "CI/CD"]', 1),
('SYSTEM_DESIGN', 'aws_eks_pipeline', 'MEDIUM', 'How do you architect a containerized deployment pipeline on AWS using EKS, ECR, and GitHub Actions?', 'Builds Docker image, pushes to ECR, and updates Helm deployment on EKS cluster via GitHub Actions.', '["AWS EKS", "ECR", "GitHub Actions"]', 1),
('SYSTEM_DESIGN', 'json_gcs_storage', 'MEDIUM', 'How do you handle large payload JSON responses without degrading database query performance?', 'Saves raw full JSON response to GCS bucket and stores GCS path string in MySQL table.', '["GCS Storage", "Performance"]', 1),
('SYSTEM_DESIGN', 'cross_encoder_rerank', 'MEDIUM', 'How do you design a document re-ranking service using cross-encoder models?', 'Passes retrieved candidate documents + query pair into cross-encoder to compute relevance scores.', '["Cross-Encoder", "Re-ranking"]', 1),
('SYSTEM_DESIGN', 'config_management', 'MEDIUM', 'How do you structure environment configuration management across dev, staging, and production environments?', 'Uses pydantic-settings BaseSettings reading environment-specific .env configurations.', '["Configuration", "Pydantic"]', 1),
('SYSTEM_DESIGN', 'redis_locks', 'MEDIUM', 'How do you design a distributed lock mechanism using Redis to prevent duplicate task execution?', 'Uses Redis SET key value NX PX milliseconds to acquire atomic lock during processing.', '["Redis Lock", "Distributed Systems"]', 1),
('SYSTEM_DESIGN', 'exponential_backoff', 'MEDIUM', 'How do you implement automated retry logic with exponential backoff for external API dependencies?', 'Retries failed HTTP calls with formula 2^retry_count * base_seconds + jitter.', '["Resilience", "Retry Logic"]', 1),
('SYSTEM_DESIGN', 'feedback_ratings', 'MEDIUM', 'How do you design a feedback collection system for user ratings on AI-generated suggestions?', 'Stores user thumbs-up/down ratings linked to query_id for continuous evaluation.', '["Feedback Loop", "User Data"]', 1),
('SYSTEM_DESIGN', 'json_schema_evolution', 'MEDIUM', 'How do you handle schema evolution for JSON columns in MySQL without breaking legacy API readers?', 'Uses additive JSON fields and default value fallbacks in Pydantic reader models.', '["Schema Evolution", "JSON"]', 1),
('SYSTEM_DESIGN', 'text_summarization_scale', 'MEDIUM', 'How do you design a scalable text summarization pipeline for large-scale customer call logs?', 'Chunks long audio transcripts, generates map-reduce summaries, and stores in DB.', '["Summarization", "LLMs"]', 1),
('SYSTEM_DESIGN', 'file_upload_security', 'MEDIUM', 'How do you structure a secure file upload pipeline with virus scanning and file type validation?', 'Validates MIME type, scans file buffer via ClamAV container, and uploads to GCS.', '["File Security", "Uploads"]', 1),
('SYSTEM_DESIGN', 'resume_parsing_pipeline', 'MEDIUM', 'How do you design a resume parsing pipeline that updates candidate profile data automatically?', 'Extracts text from PDF resume, calls LLM JSON parser, and updates candidate_resumes table.', '["Resume Parsing", "LLMs"]', 1),
('SYSTEM_DESIGN', 'graceful_degradation', 'MEDIUM', 'How do you handle graceful degradation when an upstream ML service becomes unavailable?', 'Catches service errors, returns degraded fallback response, and logs alert metrics.', '["Fault Tolerance", "Resilience"]', 1),
('SYSTEM_DESIGN', 'leaderboard_design', 'MEDIUM', 'How do you design a real-time leaderboard system for tracking practice assessment scores?', 'Uses Redis Sorted Sets (ZADD/ZREVRANGE) for fast rank lookups.', '["Redis", "Leaderboard"]', 1),
('SYSTEM_DESIGN', 'api_versioning', 'MEDIUM', 'How do you structure API versioning (/v1, /v2) in FastAPI without duplicating codebase logic?', 'Uses APIRouter prefixes (/v1, /v2) delegating shared core business logic to services layer.', '["FastAPI", "API Versioning"]', 1),
('SYSTEM_DESIGN', 'db_backup_strategy', 'MEDIUM', 'How do you design an automated database backup and point-in-time recovery (PITR) strategy?', 'Schedules automated Cloud SQL daily snapshots and continuous binary logging for PITR.', '["Database Backups", "Cloud SQL"]', 1),
('SYSTEM_DESIGN', 'dynamic_query_routing', 'MEDIUM', 'How do you implement dynamic query routing between different vector collections based on query intent?', 'Classifies user query domain intent and queries corresponding vector store collection.', '["Query Routing", "Vector DB"]', 1),
('SYSTEM_DESIGN', 'analytics_dashboard', 'MEDIUM', 'How do you design a dashboard analytics service aggregating candidate progress metrics over time?', 'Queries candidate assessment scores breakdown JSON and computes historical average trends.', '["Analytics", "Dashboard"]', 1),
('SYSTEM_DESIGN', 'event_driven_sqs', 'MEDIUM', 'How do you structure an event-driven architecture using AWS SQS and Lambda for file processing?', 'S3 triggers SQS message queue; Lambda worker process pulls message and executes processing.', '["AWS SQS", "Lambda", "Event-Driven"]', 1),
('SYSTEM_DESIGN', 'webhook_security', 'MEDIUM', 'How do you design a secure webhook receiver service with signature verification?', 'Verifies HMAC SHA-256 header signature matching secret token before processing webhook body.', '["Webhooks", "Security"]', 1),
('SYSTEM_DESIGN', 'soft_deletes', 'MEDIUM', 'How do you implement soft deletes and data retention policies in relational database schemas?', 'Uses deleted_at timestamp column and filters queries WHERE deleted_at IS NULL.', '["Soft Delete", "Database Design"]', 1),
('SYSTEM_DESIGN', 'onnx_browser_vision', 'MEDIUM', 'How do you design a browser-side ML inference pipeline using ONNX.js to protect video privacy?', 'Runs YOLOv8n ONNX model in candidate browser canvas; transmits metric numbers to backend.', '["ONNX.js", "Browser ML", "Privacy"]', 1),
('SYSTEM_DESIGN', 'frontend_wizard_state', 'MEDIUM', 'How do you build a multi-step wizard workflow on the frontend with persistent step state?', 'Stores wizard step state in React Context / LocalStorage and validates inputs at each step.', '["React", "Frontend State"]', 1);

-- SYSTEM_DESIGN: 50 HARD & EXPERT
INSERT INTO `ai_prep_question_bank` 
  (`category`, `sub_category`, `difficulty_level`, `question_text`, `ideal_answer_rubric`, `relevant_skills_json`, `is_active`)
VALUES 
('SYSTEM_DESIGN', 'agent_orchestration_scale', 'HARD', 'How do you design a high-throughput, sub-second latency multi-agent orchestration engine using LangGraph and Redis?', 'Details state persistence, async node execution, WebSocket streaming, and distributed locks.', '["LangGraph", "Orchestration", "Redis"]', 1),
('SYSTEM_DESIGN', 'multi_tenant_vector_db', 'HARD', 'How do you architect a global multi-tenant vector database infrastructure with isolated tenant collections and HNSW indexing?', 'Details tenant namespace isolation, payload indexing, replication, and memory bounds.', '["Milvus", "Vector DB", "Multi-Tenancy"]', 1),
('SYSTEM_DESIGN', 'speech_streaming_pipeline', 'HARD', 'How do you design a real-time streaming speech recognition and acoustic analysis pipeline processing thousands of simultaneous calls?', 'Details streaming WebSockets, audio chunking, Whisper/Deepgram STT, and librosa feature extraction.', '["Speech Recognition", "WebSockets", "Streaming"]', 1),
('SYSTEM_DESIGN', 'encrypted_media_pipeline', 'HARD', 'How do you build a zero-trust media processing pipeline with end-to-end encryption in transit and at rest?', 'Details TLS 1.3, client-side chunk encryption, KMS key rotation, and GCS bucket permissions.', '["Security", "KMS", "Encryption"]', 1),
('SYSTEM_DESIGN', 'event_streaming_kafka', 'HARD', 'How do you design a distributed event-driven architecture using Kafka, Schema Registry, and Flink for real-time analytics?', 'Details event topics, Avro schema validation, sliding window aggregations, and sink DB storage.', '["Kafka", "Flink", "Event-Driven"]', 1),
('SYSTEM_DESIGN', 'global_agent_platform', 'EXPERT', 'How do you architect a planetary-scale distributed multi-agent intelligence platform serving 10M+ active daily users?', 'Details global edge routing, state replication, sub-100ms multi-agent coordination, and fallbacks.', '["Global Architecture", "Multi-Agent", "Scale"]', 1),
('SYSTEM_DESIGN', 'realtime_multimodal_engine', 'EXPERT', 'How do you design a zero-latency real-time multimodal reasoning engine integrating live video feeds, spatial audio, and sensory telemetry?', 'Details zero-copy IPC memory buffers, GPU frame pipelines, and multi-modal alignment.', '["Multimodal", "Real-Time Engine", "GPU"]', 1),
('SYSTEM_DESIGN', 'self_healing_cloud', 'EXPERT', 'How do you build a distributed self-healing cloud infrastructure that automatically detects, isolates, and repairs architectural failures?', 'Details Kubernetes custom controllers, automated health probes, circuit breakers, and canary rollbacks.', '["Self-Healing Infrastructure", "Kubernetes"]', 1),
('SYSTEM_DESIGN', 'quantum_safe_storage', 'EXPERT', 'How do you design a quantum-safe end-to-end encrypted storage and communication system for sensitive enterprise AI data?', 'Details post-quantum lattice-based cryptography, KMS key encapsulation, and zero-knowledge proofs.', '["Cryptography", "Security", "Quantum-Safe"]', 1),
('SYSTEM_DESIGN', 'multi_region_vector_index', 'EXPERT', 'How do you architect a multi-region petabyte-scale vector search engine with sub-10ms global retrieval latencies?', 'Details distributed partition sharding, cross-region replication, ANN graph index compression.', '["Vector DB Engine", "Global Search", "Distributed Systems"]', 1);

-- ---------------------------------------------------------------------
-- 4. HIRING MANAGER QUESTIONS (Category: HIRING_MANAGER)
-- ---------------------------------------------------------------------
INSERT INTO `ai_prep_question_bank` 
  (`category`, `sub_category`, `difficulty_level`, `question_text`, `ideal_answer_rubric`, `relevant_skills_json`, `is_active`)
VALUES 
('HIRING_MANAGER', 'system_ownership', 'HARD', 'Tell me about an AI system or software architecture you owned end-to-end. What major trade-offs did you make?', 'Look for clear technical ownership, architectural trade-offs (e.g., latency vs accuracy, buy vs build), measurable business impact, and post-launch monitoring.', '["System Architecture", "Technical Leadership", "Ownership", "Trade-off Analysis"]', 1),
('HIRING_MANAGER', 'conflict_resolution', 'MEDIUM', 'How do you handle technical disagreements with senior engineers regarding model choice or framework selection?', 'Evaluate data-driven decision making, benchmarking, STAR format structure, and focus on team velocity and business outcomes.', '["Conflict Resolution", "Communication", "Technical Decision Making"]', 1),
('HIRING_MANAGER', 'leadership', 'HARD', 'What technical and team impact do you plan to deliver in your first 90 days as a Senior AI Engineer on our team?', 'Look for structured plan: Month 1 (onboarding, codebase understanding), Month 2 (first production feature/fix), Month 3 (process improvement, mentoring).', '["90-Day Plan", "Engineering Leadership", "Proactivity"]', 1),
('HIRING_MANAGER', 'General Management & Scenario-Based', 'MEDIUM', 'Can you describe a situation where you had to learn something new with minimal guidance?', 'Measures self-directed learning and resourcefulness.', '["Self-Learning", "Problem Solving"]', 1),
('HIRING_MANAGER', 'General Management & Scenario-Based', 'MEDIUM', 'Can you describe your transition from full stack development to data science and MLOps, and how your responsibilities evolved over time?', 'Evaluates skill evolution and MLOps transition.', '["Full Stack", "MLOps"]', 1),
('HIRING_MANAGER', 'General Management & Scenario-Based', 'HARD', 'How do you approach build-versus-buy decisions for AI tools, and what factors influence the evaluation?', 'Assesses trade-off analysis and architectural decision-making.', '["Architecture", "Build vs Buy"]', 1),
('HIRING_MANAGER', 'General Management & Scenario-Based', 'HARD', 'How do you balance precision and recall in retrieval systems, and how does the use case influence this trade-off?', 'Measures retrieval metrics understanding.', '["Retrieval", "Precision-Recall"]', 1),
('HIRING_MANAGER', 'Leadership, Collaboration & Culture', 'MEDIUM', 'Can you describe a situation where you collaborated with multiple cross-functional teams and how you ensured alignment and buy-in?', 'Evaluates stakeholder management and team collaboration.', '["Collaboration", "Communication"]', 1),
('HIRING_MANAGER', 'Leadership, Collaboration & Culture', 'MEDIUM', 'Can you share an example of mentoring or supporting less experienced team members to improve their technical skills?', 'Measures mentorship and team growth mindset.', '["Mentorship", "Leadership"]', 1),
('HIRING_MANAGER', 'Leadership, Collaboration & Culture', 'HARD', 'How do you balance hands-on technical work with principal-level responsibilities such as architecture design and team leadership?', 'Evaluates balance between execution and strategic leadership.', '["Leadership", "Architecture"]', 1),
('HIRING_MANAGER', 'Strategy, Product & Business Impact', 'HARD', 'Can you describe a past AI/ML project, including its business impact and measurable outcomes?', 'Look for quantified business metrics (e.g., latency reduction, cost savings, call handling time reduction).', '["Business Impact", "Metrics"]', 1),
('HIRING_MANAGER', 'Strategy, Product & Business Impact', 'HARD', 'How did your RAG-based solution improve key business metrics such as resolution time, accuracy, or customer satisfaction?', 'Evaluates ROI and customer impact measurement.', '["ROI", "Customer Impact"]', 1),
('HIRING_MANAGER', 'Troubleshooting & Problem Solving', 'HARD', 'A customer is saying that the AI system or AI agent that we have built gives irrelevant answers. How will you start your troubleshooting process?', 'Measures systematic debugging and root-cause analysis.', '["Troubleshooting", "Debugging", "RAG"]', 1),
('HIRING_MANAGER', 'Troubleshooting & Problem Solving', 'HARD', 'What are common failure modes in RAG systems, and how do you mitigate issues such as poor chunking, low precision/recall, or irrelevant retrievals?', 'Evaluates failure mode analysis in RAG.', '["RAG", "Chunking", "Evaluation"]', 1);

-- ---------------------------------------------------------------------
-- 5. RECRUITER QUESTIONS (Category: RECRUITER)
-- ---------------------------------------------------------------------
INSERT INTO `ai_prep_question_bank` 
  (`category`, `sub_category`, `difficulty_level`, `question_text`, `ideal_answer_rubric`, `relevant_skills_json`, `is_active`)
VALUES 
('RECRUITER', 'salary_expectations', 'EASY', 'What are your base compensation and equity expectations for your next AI Engineering role?', 'Candidate should express salary expectations clearly, articulate value proposition, and demonstrate market awareness.', '["Compensation Negotiation", "Logistics", "Professional Communication"]', 1),
('RECRUITER', 'notice_period', 'EASY', 'What is your official notice period in your current role, and how soon can you start after receiving an offer?', 'Check notice period duration (e.g., 2 weeks, 30 days) and immediate availability timeline.', '["Notice Period", "Availability", "Logistics"]', 1),
('RECRUITER', 'company_interest', 'EASY', 'Why are you looking to leave your current role right now, and what specifically attracts you to our company?', 'Evaluate positive career growth motivation rather than negative complaining about past employer.', '["Company Research", "Motivation Fit", "Career Trajectory"]', 1),
('RECRUITER', 'Availability & Start Date', 'EASY', 'Can you confirm your environment setup before starting a coding interview, including access to required platforms and tools?', 'Evaluates technical setup readiness.', '["Environment Setup"]', 1),
('RECRUITER', 'Availability & Start Date', 'EASY', 'Do you have any planned time off or commitments in the next 90 days that could impact your availability?', 'Assesses availability transparency.', '["Availability"]', 1),
('RECRUITER', 'Compensation & Salary', 'EASY', 'What compensation range are you targeting for your next AI engineering role?', 'Gauges compensation alignment.', '["Compensation"]', 1),
('RECRUITER', 'Compensation & Salary', 'MEDIUM', 'What factors influence your compensation expectations, and how flexible are you when considering different roles?', 'Measures flexibility and total compensation understanding.', '["Compensation"]', 1),
('RECRUITER', 'Interview Process', 'EASY', 'Are you actively interviewing with other companies, and if so, what stages are you currently in?', 'Tracks process stage.', '["Interview Status"]', 1),
('RECRUITER', 'Job Search Motivations & Role Fit', 'MEDIUM', 'What are you looking for in your next role as an ML or GenAI engineer, and what motivates your job search?', 'Understands role motivation.', '["Career Goals"]', 1),
('RECRUITER', 'Work Authorization & Visa', 'EASY', 'Are you authorized to work in the United States, and do you require any sponsorship now or in the future?', 'Checks work authorization status.', '["Visa", "Work Authorization"]', 1),
('RECRUITER', 'Work Model & Location', 'EASY', 'Are you comfortable with a hybrid work schedule requiring three days per week in the office?', 'Checks work model alignment.', '["Work Model", "Hybrid"]', 1);

-- ---------------------------------------------------------------------
-- 6. BEHAVIORAL / HR QUESTIONS (Category: BEHAVIORAL)
-- ---------------------------------------------------------------------
INSERT INTO `ai_prep_question_bank` 
  (`category`, `sub_category`, `difficulty_level`, `question_text`, `ideal_answer_rubric`, `relevant_skills_json`, `is_active`)
VALUES 
('BEHAVIORAL', 'star_framework', 'MEDIUM', 'Describe a complex software or AI project you led from concept to deployment. What challenges did you encounter?', 'Look for explicit STAR structure (Situation, Task, Action, Result) with clear individual contributions and quantified metrics.', '["STAR Method", "Project Management", "Problem Solving"]', 1),
('BEHAVIORAL', 'failure_recovery', 'HARD', 'Tell me about a time a model or system you deployed failed in production. How did you handle the incident post-mortem?', 'Evaluate incident management, immediate mitigation/rollback, root-cause analysis, and preventative systemic improvements.', '["Incident Response", "Post-Mortem", "Resilience", "Production Monitoring"]', 1),
('BEHAVIORAL', 'prioritization', 'MEDIUM', 'How do you prioritize technical debt reduction versus delivering new AI features under tight product deadlines?', 'Look for pragmatic trade-off analysis, risk assessment, and transparent communication with product management.', '["Technical Debt", "Prioritization", "Agile Engineering"]', 1);
