CREATE TABLE IF NOT EXISTS `candidate` (
  `id` int NOT NULL AUTO_INCREMENT,
  `full_name` varchar(100) NOT NULL,
  `enrolled_date` date DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `phone` varchar(100) DEFAULT NULL,
  `status` enum('active','discontinued','break','closed','inactive') DEFAULT 'active',
  `workstatus` varchar(100) DEFAULT NULL,
  `education` varchar(200) DEFAULT NULL,
  `workexperience` varchar(200) DEFAULT NULL,
  `ssn` varchar(11) DEFAULT NULL,
  `agreement` char(1) DEFAULT 'N',
  `secondaryemail` varchar(100) DEFAULT NULL,
  `secondaryphone` varchar(45) DEFAULT NULL,
  `address` varchar(300) DEFAULT NULL,
  `linkedin_id` varchar(200) DEFAULT NULL,
  `dob` date DEFAULT NULL,
  `emergcontactname` varchar(100) DEFAULT NULL,
  `emergcontactemail` varchar(100) DEFAULT NULL,
  `emergcontactphone` varchar(100) DEFAULT NULL,
  `emergcontactaddrs` varchar(300) DEFAULT NULL,
  `fee_paid` int DEFAULT NULL,
  `notes` text,
  `batchid` int NOT NULL,
  `candidate_folder` varchar(500) DEFAULT NULL COMMENT 'Google Drive folder link for the candidate',
  `github_link` varchar(300) DEFAULT NULL,
  `move_to_prep` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=908 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='List of enrolled candidates'