CREATE TABLE employee (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(150) DEFAULT NULL,
  email VARCHAR(150) DEFAULT NULL,
  phone VARCHAR(150) DEFAULT NULL,
  startdate DATE DEFAULT NULL,
  address VARCHAR(250) DEFAULT NULL,
  state VARCHAR(150) DEFAULT NULL,
  dob DATE DEFAULT NULL,
  enddate DATE DEFAULT NULL,
  notes TEXT,
  status TINYINT DEFAULT NULL,
  instructor TINYINT DEFAULT NULL,
  aadhaar VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY email_UNIQUE (email),
  UNIQUE KEY aadhar (aadhaar)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='Employee Management';
