CREATE TABLE IF NOT EXISTS`automation_workflow_logs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `workflow_id` bigint unsigned NOT NULL,
  `schedule_id` bigint unsigned DEFAULT NULL,
  `run_id` varchar(64) NOT NULL,
  `status` enum('queued','running','success','failed','partial_success','timed_out') NOT NULL DEFAULT 'queued',
  `parameters_used` json DEFAULT NULL,
  `execution_metadata` json DEFAULT NULL,
  `records_processed` int unsigned DEFAULT '0',
  `records_failed` int unsigned DEFAULT '0',
  `error_summary` varchar(255) DEFAULT NULL,
  `error_details` longtext,
  `started_at` datetime(6) DEFAULT NULL,
  `finished_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `fk_log_schedule` (`schedule_id`),
  KEY `idx_log_workflow_status` (`workflow_id`,`status`),
  KEY `idx_log_run_id` (`run_id`),
  KEY `idx_log_created` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=145 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
