CREATE TABLE IF NOT EXISTS `job_listing` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `normalized_title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'standardized role name',
  `company_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `company_id` int DEFAULT NULL COMMENT 'future reference to company table',
  `position_type` enum('full_time','contract','contract_to_hire','internship') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'full_time',
  `employment_mode` enum('onsite','hybrid','remote') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'hybrid',
  `source` enum('bot_linkedin_post_contact_extractor','bot_linkedin_message_extraction','email','linkedin','job_board','scraper','hiring.cafe','interview_modal','email_bot_llm_local') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'linkedin' COMMENT 'source of job extraction',
  `source_uid` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `location` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `city` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `state` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `zip` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `country` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contact_email` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contact_phone` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contact_linkedin` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `job_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` mediumtext COLLATE utf8mb4_unicode_ci,
  `notes` text COLLATE utf8mb4_unicode_ci,
  `status` enum('open','closed','on_hold','duplicate','invalid') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'open',
  `confidence_score` decimal(5,2) DEFAULT NULL COMMENT 'extraction or matching confidence',
  `created_from_raw_id` bigint DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `source_job_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_company` (`company_name`),
  KEY `idx_status` (`status`),
  KEY `idx_location` (`state`,`city`,`zip`)
) ENGINE=InnoDB AUTO_INCREMENT=10823 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Cleaned and approved job positions'